const apiResult = [{
    title:"qotanski",
    Color1: "#111",
    Color2: "yellow",
    Color3: "",
    Color4: "",
    Color5: "",
    Color6: "",
    Color7: "",
    Price: "12",
    Size1: "20",
    Size2: "30",
    Size3: "33"
  },{
    title:"qotanski",
    Color1: "#111",
    Color2: "yellow",
    Color3: "",
    Color4: "",
    Color5: "",
    Color6: "",
    Color7: "",
    Price: "12",
    Code: "pot1",
    Size1: "20",
    Size2: "30",
    Size3: "33"
  },{
    title:"qotanski",
    Color1: "#111",
    Color2: "yellow",
    Color3: "",
    Color4: "",
    Color5: "",
    Color6: "",
    Color7: "",
    Price: "12",
    Code: "pot1",
    Size1: "20",
    Size2: "30",
    Size3: "33"
  },{
    title:"qotanski",
    Color1: "#111",
    Color2: "yellow",
    Color3: "",
    Color4: "",
    Color5: "",
    Color6: "",
    Color7: "",
    Price: "12",
    Code: "pot1",
    Size1: "20",
    Size2: "30",
    Size3: "33"
  },{
    title:"qotanski",
    Color1: "#111",
    Color2: "yellow",
    Color3: "",
    Color4: "",
    Color5: "",
    Color6: "",
    Color7: "",
    Price: "12",
    Code: "pot1",
    Size1: "20",
    Size2: "30",
    Size3: "33"
  },];